// The Material workspace as a user drives it: tab 7, open a material, Space menu, wire drag, Delete never removes a
// layer, undo, inline value drag, save / open project, export zip, material → layer, back to Type.
import { open, check, done } from './_launch.mjs';
const { browser, page: p, errors } = await open();
const ev = (f, a) => p.evaluate(f, a);
await ev(() => { const L = TL.make.text({ text: 'HELLO', x: 300, y: 300 }); TL.addLayer(L); TL.select(L.id); TL.commit('t'); TL.emit('layers'); });
await p.keyboard.press('7'); await p.waitForTimeout(800);
check(await ev(() => TL.st.mode) === 'material', 'key 7 opens the Material workspace');
check(await ev(() => getComputedStyle(document.getElementById('view')).display === 'none' && !document.getElementById('matgraph').hidden), 'graph replaces the canvas');
await ev(() => TL.mat.newFromPreset('red-bricks')); await p.waitForTimeout(2500);
check(await p.locator('.mg-node').count() > 5, 'preset opens as a node graph');
const g = await p.locator('.mg-wrap').boundingBox();
await p.mouse.move(g.x + 200, g.y + g.height - 150);
await p.keyboard.down(' '); await p.keyboard.up(' '); await p.waitForTimeout(300);
check(await p.locator('.mg-menu').count() === 1, 'Space opens the add-node menu');
await p.keyboard.type('voronoi'); await p.keyboard.press('Enter'); await p.waitForTimeout(800);
check(await ev(() => TL.mat.current().nodes.some((n) => n.type === 'voronoi')), 'typing + Enter adds the node');
const vor = p.locator('.mg-node', { hasText: 'Voronoi' }).last();
const a = await vor.locator('.mg-port.out[data-idx="1"]').boundingBox(), c = await p.locator('.mg-node.output .mg-port.in[data-idx="2"]').boundingBox();
await p.mouse.move(a.x + a.width / 2, a.y + a.height / 2); await p.mouse.down();
await p.mouse.move((a.x + c.x) / 2, (a.y + c.y) / 2, { steps: 5 }); await p.mouse.move(c.x + c.width / 2, c.y + c.height / 2, { steps: 5 }); await p.mouse.up();
await p.waitForTimeout(600);
check(await ev(() => { const m = TL.mat.current(), o = TL.mat.output(m), l = TL.mat.inLink(m, o.id, 2); return !!l && TL.mat.node(m, l.from).type === 'voronoi'; }), 'dragging output → input connects');
await vor.locator('.mg-head').click(); await p.keyboard.press('Delete'); await p.waitForTimeout(400);
check(await ev(() => !TL.mat.current().nodes.some((n) => n.type === 'voronoi')), 'Delete removes the selected node');
check(await ev(() => TL.doc.layers.length) === 1, 'Delete in the graph never deletes a layer');
await p.keyboard.press('Control+z'); await p.waitForTimeout(600);
check(await ev(() => TL.mat.current().nodes.some((n) => n.type === 'voronoi')), 'Ctrl+Z brings the node back');
const rows = p.locator('.mg-node', { hasText: 'Bricks' }).first().locator('.mg-param[data-k="rows"]');
const rb = await rows.boundingBox(); const before = await ev(() => TL.mat.current().nodes.find((n) => n.type === 'bricks').p.rows);
await p.mouse.move(rb.x + 20, rb.y + rb.height / 2); await p.mouse.down(); await p.mouse.move(rb.x + 80, rb.y + rb.height / 2, { steps: 6 }); await p.mouse.up(); await p.waitForTimeout(500);
check(await ev(() => TL.mat.current().nodes.find((n) => n.type === 'bricks').p.rows) > before, 'dragging a value on a node changes it');
await ev(() => TL.exp.saveProject()); await p.waitForTimeout(400);
const saved = await ev(() => new TextDecoder().decode(window.__saved.data));
check(JSON.parse(saved).doc.materials.length === 1, 'materials are saved in the .typelab project');
await ev(async (txt) => { TL.newDoc(800, 600); TL.emit('doc'); await TL.exp.loadProject(new File([txt], 'p.typelab')); }, saved); await p.waitForTimeout(1200);
check(await ev(() => TL.doc.materials.length === 1 && TL.doc.materials[0].nodes.length > 5), 'materials come back when the project is opened');
await ev(async () => { TL.mat.ui.exp.size = 512; await TL.mat.exportZip(TL.mat.current()); }); await p.waitForTimeout(300);
check(await ev(() => /_maps\.zip$/.test(window.__saved.defaultPath) && window.__saved.data.length > 10000), 'export maps writes a zip');
await ev(() => TL.mat.toLayer(TL.mat.current(), 4, true)); await p.waitForTimeout(400);
check(await ev(() => TL.doc.layers.some((l) => l.type === 'image')), 'material → image layer');
await p.keyboard.press('1'); await p.waitForTimeout(1000);
check(await ev(() => TL.st.mode === 'type' && getComputedStyle(document.getElementById('view')).display !== 'none' && document.getElementById('matgraph').hidden), 'back in Type the canvas is visible again');
await done(browser, errors);
